package com.theathletic.compass.codegen

import com.theathletic.compass.Experiment
import com.theathletic.compass.ICompassExperiment
import com.theathletic.compass.Variant
import com.theathletic.debugtools.DebugPreferences
import com.theathletic.utility.logging.ICrashLogHandler
import kotlin.String
import kotlin.collections.HashMap
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject

public data class VariantKey(
    public val expName: String,
    public val variantId: String
)

/**
 * This class was generated by the 'compass' plugin
 */
public object CompassExperiment : ICompassExperiment(), KoinComponent {
    public val crashLogHandler: ICrashLogHandler by inject<ICrashLogHandler>()

    public val debugPreferences: DebugPreferences by inject<DebugPreferences>()

    public val HOME_ADS_V2: HomeAdsV2
        get() = experimentMap["Home Ads v2"] as HomeAdsV2

    public val ANDROID_PUSH_PRE_PROMPT: AndroidPushPrePrompt
        get() = experimentMap["Android Push Pre Prompt"]!! as AndroidPushPrePrompt

    public override var experimentMap: HashMap<String, Experiment> = hashMapOf(
        "Home Ads v2" to HomeAdsV2(crashLogHandler = crashLogHandler, debugPreferences = debugPreferences),
        "Android Push Pre Prompt" to AndroidPushPrePrompt(
            crashLogHandler = crashLogHandler, debugPreferences =
            debugPreferences
        )
    )


    public override val variantMap: HashMap<VariantKey, Variant> = hashMapOf(
        VariantKey(HOME_ADS_V2.name, HomeAdsV2.HomeAdsV2Variant.A()._name) to HomeAdsV2.HomeAdsV2Variant.A(),
        VariantKey(HOME_ADS_V2.name, HomeAdsV2.HomeAdsV2Variant.CTRL()._name) to HomeAdsV2.HomeAdsV2Variant.CTRL(),
        VariantKey(
            ANDROID_PUSH_PRE_PROMPT.name,
            AndroidPushPrePrompt.AndroidPushPrePromptVariant.A()._name
        ) to
                AndroidPushPrePrompt.AndroidPushPrePromptVariant.A(),
        VariantKey(
            ANDROID_PUSH_PRE_PROMPT.name,
            AndroidPushPrePrompt.AndroidPushPrePromptVariant.CTRL()._name
        ) to
                AndroidPushPrePrompt.AndroidPushPrePromptVariant.CTRL(),
    )

}
